name: Matt's GitHub Actions Demo
description: This is Matt's test of moving an action to a different org. Don't us this action!
author: matt@mattcalhoun.com.com
branding:
  icon: "terminal"
  color: "white"
runs:
  using: "composite"
  steps:
    - id: test
      shell: bash
      run: |
        echo "Hello, world! from action"
